=== CJSCommonPlatform/framework-libraries/framework-libraries-old/json-transformer/json-transformer-jolt/src/test/resources/case_details_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "caseId": {
      "type": "string"
    },
    "caseReference": {
      "type": "string"
    },
    "prosecutingAuthority": {
      "type": "string"
    },
    "_is_charging": {
      "type": "string"
    },
    "parties": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "organisationName": {
              "type": "string"
            },
            "_party_type": {
              "type": "string"
            }
          },
          "required": [
            "organisationName",
            "_party_type"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "firstName": {
              "type": "string"
            },
            "middleName": {
              "type": "string"
            },
            "lastName": {
              "type": "string"
            },
            "dateOfBirth": {
              "type": "string"
            },
            "gender": {
              "type": "string"
            },
            "addressLines": {
              "type": "string"
            },
            "postCode": {
              "type": "string"
            },
            "pncId": {
              "type": "string"
            },
            "aliases": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            },
            "arrestSummonsNumber": {
              "type": "string"
            },
            "_party_type": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "firstName",
            "middleName",
            "lastName",
            "dateOfBirth",
            "gender",
            "addressLines",
            "postCode",
            "pncId",
            "aliases",
            "arrestSummonsNumber",
            "_party_type"
          ]
        }
      ]
    },
    "_case_type": {
      "type": "string"
    },
    "_is_sjp": {
      "type": "boolean"
    },
    "_is_magistrates": {
      "type": "boolean"
    },
    "_is_crown": {
      "type": "boolean"
    }
  },
  "required": [
    "caseId",
    "caseReference",
    "prosecutingAuthority",
    "_is_charging",
    "parties",
    "_case_type",
    "_is_sjp",
    "_is_magistrates",
    "_is_crown"
  ]
}

=== CJSCommonPlatform/framework-libraries/framework-libraries-old/json-transformer/json-transformer-jolt/src/test/resources/case_details.json
{
  "caseId": "2279b2c3-b0d3-4889-ae8e-1ecc20c39e27",
  "caseReference": "TFL12345",
  "prosecutingAuthority": "TFL",
  "_is_charging": "J",
  "parties": [
    {
      "_party_type": "Defendant"
    },
    {
      "title": "MR",
      "firstName": "Harry",
      "middleName": "Jack",
      "lastName": "Kane Junior",
      "dateOfBirth": "2010-01-01",
      "gender": "MALE",
      "addressLines": "\"22\",\"Acacia Avenue\",\"Acacia Town\",\"Acacia City\",\"Acacia Country\"",
      "postCode": "GIR 0AA",
      "pncId": "1234567",
      "aliases": [
        "johnny robber",
        "jack the knife"
      ],
      "arrestSummonsNumber": "arrest123"
    }
  ],
  "_case_type": "CC",
  "_is_sjp": true,
  "_is_magistrates": true,
  "_is_crown": false
}
